backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Subheading2, name: subheading2, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/menu/index.md"
        label: "Menu Page"
        name: "menu"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "menu-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Main,
              name: main,
              widget: object,
              fields: [
                {
                  label: Menu Section,
                  name: menu_sections,
                  widget: object,
                  fields: {
                    {
                      label: Snacks,
                      name: snacks,
                      widget: object,
                      fields: {
                        {
                          label: Items,
                          name: items,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string },
                            { label: Price2, name: price2, widget: string, required: false }
                          ]
                        }
                      }
                    },
                    {
                      label: French Fries,
                      name: french_fries,
                      widget: object,
                      fields: [
                        { label: Base Price, name: base_price, widget: string },
                        {
                          label: Sections,
                          name: sections,
                          widget: list,
                          fields: [
                            { label: Title, name: title, widget: string },
                            { 
                              label: Items,
                              name: items,
                              widget: list,
                              fields: [
                                { label: Name, name: name, widget: string },
                                { label: Price, name: price, widget: string, required: false }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      label: Salads,
                      name: salads,
                      widget: object,
                      fields: [
                        {
                          label: Items,
                          name: items,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string },
                            { label: Description, name: description, widget: string }
                          ]
                        },
                        {
                          label: Salad Proteins,
                          name: salad_proteins,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string }
                          ]
                        }
                      ]
                    },
                    {
                      label: Sandwiches,
                      name: sandwiches,
                      widget: object,
                      fields: [
                        {
                          label: Items,
                          name: items,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string },
                            { label: Description, name: description, widget: string }
                          ]
                        },
                        {
                          label: Sides,
                          name: sides,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string }
                          ]
                        }
                      ]
                    },
                    {
                      label: Pizza,
                      name: pizza,
                      widget: list,
                      fields: [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                        { label: Description, name: description, widget: string }
                      ]
                    },
                    {
                      label: BYOP,
                      name: byop,
                      widget: object,
                      fields: [
                        { label: Base Price, name: base_price, widget: string },
                        {
                          label: Sections,
                          name: sections,
                          widget: list,
                          fields: [
                            { label: Header,
                              name: header,
                              widget: object,
                              fields: [
                                { label: Title, name: title, widget: string },
                                { label: Price, name: price, widget: string, required: false }
                              ]
                            },
                            { 
                              label: Items,
                              name: items,
                              widget: list,
                              fields: [
                                { label: Name, name: name, widget: string },
                                { label: Price, name: price, widget: string, required: false }
                              ]
                            }
                          ]
                        }
                        
                      ]
                    },
                    {
                      label: Garlic Knots,
                      name: garlic_knots,
                      widget: list,
                      fields: [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string }
                      ]
                    },
                    {
                      label: Something Sweet,
                      name: something_sweet,
                      widget: list,
                      fields: [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string }
                      ]
                    },
                    {
                      label: Kids Stuff,
                      name: kids_stuff,
                      widget: object,
                      fields: [
                        { label: Base Price, name: base_price, widget: string }
                        {
                          label: Items,
                          name: items,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string, required: false }
                          ]
                        }
                      ]
                    },
                    {
                      label: Cocktails,
                      name: cocktails,
                      widget: list,
                      fields: [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                        { label: Description, name: description, widget: string }
                      ]
                    },
                    {
                      label: Wine and Beer,
                      name: wine_beer,
                      widget: object,
                      fields: [
                        {
                          label: Wine,
                          name: wine,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string }
                          ]
                        },
                        {
                          label: Beer,
                          name: beer,
                          widget: list,
                          fields: [
                            { label: Name, name: name, widget: string },
                            { label: Price, name: price, widget: string }
                          ]
                        }
                      ]
                    },
                    {
                      label: N/A Beverages,
                      name: na_bevs,
                      widget: list,
                      fields: [
                        { label: Name, name: name, widget: string },
                        { label: Price, name: price, widget: string },
                      ]
                    }
                  }
                }
              ]
          }
          - { label: "Body", name: "body", widget: "markdown" }

      
